  const textOptions = [
    "hold your horses!", 
    "slow down there partner!",
    "i can't- i can't shut it down!",
    "let me tell you something!",
    "warning!",
    "not my proudest one!",
    "now just hold on a minute!",
    "danger ahead!",
    "times are rough!",
    "you know, they say the sick delude themselves!",
    "crispy critters!",
    "i just need faith!",
    "you're doubting me!",
    "choom, it's fucked!",
    "catch me later, i'll buy you a beer!",
    "i've never seen it lit up like that!",
    "another brilliant lamar davis production!",
    "the end is never the end!",
    "ah fiddlesticks! what now?",
    "i've got you now black lung!",
    "damn us all!",
    "as if i didn't know it, brad!",
    "i tought i told you to run!",
    "come on joburg, shot number three!",
    "you me and arasaka tower!",
    "whoop there it is!",
    "and there's always a god damn train!",
    "all of your theories are wrong!",
    "i hate to break it you...",
    "good people don't end up here.",
    "mestermc-auth-mod-1.0.0-dev-obf.jar",
    "teto",
    "teto nem vocaloid bro :steamfacepalm:",
    ":fefe:",
    "that was my money tommy!",
    "ay niko watch out there's bad man coming!",
    "let's make the most of the night like we're gonna die young!",
    "colonel kurt hansen is dead! i repeat, kurt hansen is dead!",
    "this is druuug money!",
    "oiia oiia",
    "xiao hong shuuu!!!!!!",
    "green light green light, martin madrazo gives you the green light!",
    "can you hear me?",
    "may i stand unshaken.",
    "cruel cruel world, must i go on?",
    "i've been living too fast and i've been living too wrong.",
    "anis my beloved!!",
    "woof woof woof arf arf arf!!!",
    "what in the fuck?",
    "you fell, unfortunately it was funny!",
    "i've had a difficult childhood!",
    "pisi.png",
    "you are the youngest person ever!",
    "da gloop go off?",
    "you ruined my life!",
    "did someone say yoga?",
    "no, no yoga!",
    "and i think that's all the time we had!",
    "same time next week?",
    "15 dollars and a quarter. don't forget the quarter!",
    "you know other women?!",
    "cro vented!!!!",
    "man i've got bad bitches at the criib. FUCK YOU MEAN?!",
    "where they at doe?",
    "uncle bao bao!!!!",
    "what kind of watermelon is this?",
    "this is a giant watermelon!",
    "xxx tempapon unter der maske. er lept.",
    "biddybud.",
    "when yoe beating yoe shit and you accidentally click the powa button.",
    "hello niche community!",
    "gem alert!!!!",
    "coal alert!!!!",
    "what kind of cicada is this?",
    "i'm diamond oonnee!!",
    "schikinburge",
    "doro doro",
    "i am the face of bejing corn!",
    "i'm spunchbob!",
    "magyar peter gecije hmmmmm 🐎🐎🐎🐎🪜🪜🪜🪜🪜 arthur mo",
    "in GTA V, press and hold TAB to open your weapon wheel! 🧠💯",
    



    
    

];
  const randomIndex = Math.floor(Math.random() * textOptions.length);
  const randomWarn = textOptions[randomIndex];
  document.getElementById("randomWarn").textContent = randomWarn;